import { type Plugin } from 'vite'
import { execSync } from 'child_process'
import fs from 'fs'
import path from 'path'

/**
 * Vite plugin that adds a local-only API for deploying site data.
 * Available ONLY in dev mode — the production build has no server.
 *
 * POST /api/deploy  { data: SiteData }
 *   → writes to src/data/defaultData.ts (with a new DATA_VERSION)
 *   → git add + commit + push
 *   → Vercel auto-deploys, visitors get fresh data (old localStorage is discarded)
 */
export function deployPlugin(): Plugin {
  return {
    name: 'deploy-plugin',
    configureServer(server) {
      server.middlewares.use('/api/deploy', async (req, res) => {
        // CORS
        res.setHeader('Access-Control-Allow-Origin', '*')
        res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS')
        res.setHeader('Access-Control-Allow-Headers', 'Content-Type')
        if (req.method === 'OPTIONS') { res.statusCode = 200; res.end(); return }
        if (req.method !== 'POST') { res.statusCode = 405; res.end('Method not allowed'); return }

        // Read body
        let body = ''
        for await (const chunk of req) body += chunk
        try {
          const { data, commitMsg } = JSON.parse(body)
          if (!data) { res.statusCode = 400; res.end(JSON.stringify({ ok: false, error: 'Missing data' })); return }

          // Generate a unique version for this deploy
          const version = String(Date.now())

          // Generate the new defaultData.ts content
          const tsContent = generateDefaultDataTs(data, version)

          // Write file
          const filePath = path.resolve(process.cwd(), 'src/data/defaultData.ts')
          fs.writeFileSync(filePath, tsContent, 'utf-8')

          // Git add + commit + push
          const msg = commitMsg || `update: site data via admin panel (${new Date().toLocaleString('th-TH')})`
          try {
            execSync('git add src/data/defaultData.ts', { cwd: process.cwd(), stdio: 'pipe' })
            execSync(`git commit -m "${msg}"`, { cwd: process.cwd(), stdio: 'pipe' })
            execSync('git push', { cwd: process.cwd(), stdio: 'pipe', timeout: 30000 })
          } catch (gitErr: any) {
            const stderr = gitErr.stderr?.toString() || gitErr.message
            if (stderr.includes('nothing to commit')) {
              res.statusCode = 200
              res.end(JSON.stringify({ ok: true, message: 'ไม่มีการเปลี่ยนแปลง — ข้อมูลเหมือนเดิม' }))
              return
            }
            res.statusCode = 500
            res.end(JSON.stringify({ ok: false, error: `Git error: ${stderr}` }))
            return
          }

          res.statusCode = 200
          res.end(JSON.stringify({ ok: true, message: 'Deploy สำเร็จ! Vercel จะอัปเดตภายใน 1-2 นาที' }))
        } catch (err: any) {
          res.statusCode = 500
          res.end(JSON.stringify({ ok: false, error: err.message }))
        }
      })
    },
  }
}

/* ── Generate TypeScript file from data ── */
function generateDefaultDataTs(data: any, version: string): string {
  const lines = [
    `/* ==============================================`,
    `   Default data for the entire landing page.`,
    `   Auto-generated by admin deploy system.`,
    `   Last updated: ${new Date().toISOString()}`,
    `   ============================================== */`,
    ``,
    `export interface ContactChannel {`,
    `  id: string`,
    `  name: string`,
    `  value: string`,
    `  link: string`,
    `  iconType: 'line' | 'facebook' | 'phone' | 'email' | 'instagram' | 'tiktok' | 'telegram' | 'custom'`,
    `}`,
    ``,
    `export interface Product {`,
    `  id: string`,
    `  name: string`,
    `  desc: string`,
    `  highlight: string`,
    `  iconType: 'database' | 'shield' | 'chart' | 'chat' | 'shop' | 'gear'`,
    `  image?: string`,
    `  brand?: string`,
    `}`,
    ``,
    `export interface PricingPlan {`,
    `  id: string`,
    `  name: string`,
    `  nameTh: string`,
    `  price: string`,
    `  period: string`,
    `  desc: string`,
    `  features: { text: string; included: boolean }[]`,
    `  featured: boolean`,
    `  cta: string`,
    `}`,
    ``,
    `export interface Review {`,
    `  id: string`,
    `  name: string`,
    `  role: string`,
    `  text: string`,
    `  rating: number`,
    `  avatar: string`,
    `}`,
    ``,
    `export interface FAQItem {`,
    `  id: string`,
    `  q: string`,
    `  a: string`,
    `}`,
    ``,
    `export interface BrandInfo {`,
    `  name: string`,
    `  tagline: string`,
    `  description: string`,
    `}`,
    ``,
    `export type SectionType = 'hero' | 'products' | 'benefits' | 'pricing' | 'reviews' | 'faq' | 'contact'`,
    ``,
    `export interface SectionLayout {`,
    `  id: string`,
    `  type: SectionType`,
    `  label: string`,
    `  visible: boolean`,
    `}`,
    ``,
    `export interface SiteData {`,
    `  version: string`,
    `  layout: SectionLayout[]`,
    `  brand: BrandInfo`,
    `  contacts: ContactChannel[]`,
    `  products: Product[]`,
    `  pricing: PricingPlan[]`,
    `  reviews: Review[]`,
    `  faqs: FAQItem[]`,
    `}`,
    ``,
    `/*`,
    `  DATA_VERSION changes every time the admin deploys new data.`,
    `  If the version in localStorage doesn't match, we discard the old cache.`,
    `*/`,
    `export const DATA_VERSION = '${version}'`,
    ``,
    `/* ---------- helpers ---------- */`,
    `let _counter = 0`,
    'export function genId(): string {',
    '  return `id_${Date.now()}_${++_counter}`',
    `}`,
    ``,
    `/* ---------- defaults ---------- */`,
    ``,
    `export const defaultContacts: ContactChannel[] = ${JSON.stringify(data.contacts, null, 2)}`,
    ``,
    `export const defaultProducts: Product[] = ${JSON.stringify(data.products, null, 2)}`,
    ``,
    `export const defaultPricing: PricingPlan[] = ${JSON.stringify(data.pricing, null, 2)}`,
    ``,
    `export const defaultReviews: Review[] = ${JSON.stringify(data.reviews, null, 2)}`,
    ``,
    `export const defaultFaqs: FAQItem[] = ${JSON.stringify(data.faqs, null, 2)}`,
    ``,
    `export const defaultBrand: BrandInfo = ${JSON.stringify(data.brand, null, 2)}`,
    ``,
    `export const defaultLayout: SectionLayout[] = ${JSON.stringify(data.layout || [], null, 2)}`,
    ``,
    `export const defaultSiteData: SiteData = {`,
    `  version: DATA_VERSION,`,
    `  layout: defaultLayout,`,
    `  brand: defaultBrand,`,
    `  contacts: defaultContacts,`,
    `  products: defaultProducts,`,
    `  pricing: defaultPricing,`,
    `  reviews: defaultReviews,`,
    `  faqs: defaultFaqs,`,
    `}`,
    ``,
  ]
  return lines.join('\n')
}
