/* =============================================
   Default data for the entire landing page.
   This file is auto-generated by the admin deploy system.
   Last updated: 2026-05-09T09:18:31.189Z
   ============================================= */

export interface ContactChannel {
  id: string
  name: string
  value: string
  link: string
  iconType: 'line' | 'facebook' | 'phone' | 'email' | 'instagram' | 'tiktok' | 'telegram' | 'custom'
}

export interface Product {
  id: string
  name: string
  desc: string
  highlight: string
  iconType: 'database' | 'shield' | 'chart' | 'chat' | 'shop' | 'gear'
}

export interface PricingPlan {
  id: string
  name: string
  nameTh: string
  price: string
  period: string
  desc: string
  features: { text: string; included: boolean }[]
  featured: boolean
  cta: string
}

export interface Review {
  id: string
  name: string
  role: string
  text: string
  rating: number
  avatar: string
}

export interface FAQItem {
  id: string
  q: string
  a: string
}

export interface BrandInfo {
  name: string
  tagline: string
  description: string
}

export interface SiteData {
  brand: BrandInfo
  contacts: ContactChannel[]
  products: Product[]
  pricing: PricingPlan[]
  reviews: Review[]
  faqs: FAQItem[]
}

/* ---------- helpers ---------- */
let _counter = 0
export function genId(): string {
  return `id_${Date.now()}_${++_counter}`
}

/* ---------- defaults ---------- */

export const defaultContacts: ContactChannel[] = undefined

export const defaultProducts: Product[] = undefined

export const defaultPricing: PricingPlan[] = undefined

export const defaultReviews: Review[] = undefined

export const defaultFaqs: FAQItem[] = undefined

export const defaultBrand: BrandInfo = undefined

export const defaultSiteData: SiteData = {
  brand: defaultBrand,
  contacts: defaultContacts,
  products: defaultProducts,
  pricing: defaultPricing,
  reviews: defaultReviews,
  faqs: defaultFaqs,
}
